Show inherited configuration properties in the UI
adobe/commerce-cif-connector pull request #143
Opened 2020-07-21 06:58 UTC by laurentiumagureanu

## Description

This feature allows creation of configurations that inherit properties (enabled by default) and override just the necessary ones. 
This is inline with the "inherited properties" pattern used everywhere in AEM.

## Related Issue

CIF-1326

## Motivation and Context

Alignment with the "inherited properties" pattern used everywhere in AEM.

## How Has This Been Tested?

Manually

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

2020-07-21 13:47 UTC, herzog31 reviewed
Please don't forget about testing :)

2020-07-21 13:47 UTC, herzog31 commented on bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/servlets/ConfigurationInheritanceServlet.java
> +                while (parentConfigContainerResource != null && !parentConfigContainerResource.getPath().equals("/conf")) {
Here you're checking for inheritance within `/conf`. What about `/libs/settings/cloudconfigs/commerce` and a potential overlay in `/apps`?

2020-07-21 13:47 UTC, herzog31 commented on bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/servlets/ConfigurationInheritanceServlet.java
> +            JSONObject config = new JSONObject();
I'm a bit selfish here 😁  Could you please refactor the crawling logic into a separate class so we could also use it for CIF-1523?

2020-07-22 06:14 UTC, dplaton requested changes
As @herzog31 pointed out, we should aim to make the "crawling" logic reusable.

2020-07-27 08:24 UTC, herzog31 approved these changes

2020-07-27 08:56 UTC, dplaton approved these changes

2020-07-30 08:00 UTC, merged